var EnumStatus = Object.freeze({
    OK: 'OK',
    ILLEGAL: 'ILLEGAL',
    FAILED: 'FAILED',
    AUTH_FAILED: 'AUTH_FAILED',
    HINT_OVER: 'ENUM_HINT_STATUS_OVER',
    HINT_COOLDOWN: 'ENUM_HINT_STATUS_COOLDOWN',
    LEVEL_DONE: 'ENUM_STATUS_LEVEL_DONE',
    BW_COOLDOWN: 'ENUM_STATUS_BW_COOLDOWN',
    LOST: 'ENUM_STATUS_LOST'
});